version: "3"

services:
  web-app-1:
    image: manjuappu1375/highway
    container_name: web-app-1
    ports:
      - 81:80
    volumes:
      - web1_data:/usr/share/nginx/html

  web-app-2:
    image: manjuappu1375/minifin
    container_name: web-app-2
    ports:
      - 82:80
    volumes:
      - web2_data:/usr/share/nginx/html

  web-app-3:
    image: manjuappu1375/mosoin
    container_name: web-app-3
    ports:
      - 83:80
    volumes:
      - web3_data:/usr/share/nginx/html

volumes:
  web1_data:
  web2_data:
  web3_data:
